FROM oven/bun:1

WORKDIR /app

COPY package.json bun.lock ./

RUN bun install

COPY . .

RUN bun build ./src/index.ts --outfile=./dist/index.js

EXPOSE 5171

CMD ["bunx", "serve", ".", "-l", "tcp://0.0.0.0:5172"]